# Generated by Django 3.2 on 2021-04-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('issue_date', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=15)),
                ('book_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_register.book')),
            ],
        ),
    ]
